<?php

/**
 * @author: Elton Assunção <ewa.soft@gmail.com>, Elton John:ewati.com.br
 * @versão: 1.0
 * @copyright: (c) 2015,ewari.com.br
 * @description: Classe responsável por dar permissões Anonimas (sem necessidade de estar logado) as rotas solicitadas
 */

####PREVENÇÃO CONTRA ATAQUES Csrf####
define('REQUEST_FORGERY', FALSE);

####ATENTICAÇÃO POR MEIO DE SESSÃO DE USUARIO####
## NECESSARIO O REGISTRO DA CLASSE 'session' NA CONFIGURAÇÃO AUTO_LOAD LIBRARY;
define("AUTENTICATE", FALSE);


####PARA OS CONTROLER GERÊNCIAR TRASANÇÕES COM O BANCO####
## NECESSARIO O REGISTRO DA CLASSE 'database' NA CONFIGURAÇÃO AUTO_LOAD LIBRARY;
define("TRANSACTION_DATABASE", FALSE);


####PARA OS CONTROLER GERÊNCIAR TRASANÇÕES COM O BANCO####
## NECESSARIO O REGISTRO DA CLASSE 'database' NA CONFIGURAÇÃO AUTO_LOAD LIBRARY;
define("MAPPER_ROUTER", TRUE);


## INFORME O DIRETORIO ONDE ESTÃO AS CLASSES DE NEGOCIOS.
## ESSES DIRETORIOS PRECISAM ESTAR DENTRO DE APLICATION;
## CLASSES ESSAS QUE PRECISAM SER INJETADAS NO CONTROLLER;
## CASO NADA FOR INFORMADO ELE PEGADA DO DIRETORIO MODELS.
define("INJECT_MODEL", 'models/Cadastro');

## OBRIGA O USUARIO A TER TODOS OS ATRIBUTOS NA CLASSE,
## QUE SERÃO PASSADOS NA REQUISIÇÃO PARA CLASSE A SER INJETADAS.
## EXEMPLO-> PRODUTO->ID SE FOR PASSADO UM JSON SEM A PROPRIEDADE ID RETORNADA UM ERRO.
define("REQUIRED_PROPERTIES_INJECTOR", true);

## Libs externas separados por pont e virgula
define("DIR_LIBS", 'mpdf60');



